name: publish plugin

on:
  workflow_call:
    inputs:
      channel:
        description: 'The channel to publish the plugin to'
        required: true
        type: string
        default: 'beta'


jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: v1-gradle-caches-${{ hashFiles('settings.gradle.kts') }}-${{ hashFiles('build.gradle.kts') }}-${{ hashFiles('gradle.properties') }}
      - uses: actions/cache@v4
        with:
          path: ~/.gradle/wrapper
          key: v1-gradle-wrapper-${{ hashFiles('settings.gradle.kts') }}-${{ hashFiles('build.gradle.kts') }}-${{ hashFiles('gradle.properties') }}
      - name: echo channel
        run: echo ${{ inputs.channel }}
      - name: echo ver
        run: echo ${TAG_NAME#refs/tags/beta-}

#      - name: Release
#        env:
#          TAG_NAME: ${{ github.ref }}
#          HUB_TOKEN: ${{ secrets.HUB_TOKEN }}
#        run: ./gradlew buildPlugin publishPlugin -DVERSION=${TAG_NAME#refs/tags/beta-} -DCHANNELS=${{ inputs.channel }}
