name: release to beta

on:
  push:
    tags:
      - 'beta-*'

jobs:
  test:
    uses: ./.github/workflows/_test.yml
  verify:
    uses: ./.github/workflows/_verify.yml
  release:
    needs: [ test, verify ]
    uses: ./.github/workflows/_publish.yml
    with:
      channel: 'beta'
