name: release

on:
  push:
    tags:
      - 'release-*'

jobs:
  test:
    uses: ./.github/workflows/_test.yml
  verify:
    uses: ./.github/workflows/_verify.yml
  release:
    needs: [ test, verify ]
    uses: ./.github/workflows/_publish.yml
    with:
      channel: 'default'